### ISSUE TITLE
Doesn't work in Windows 11 // Chrome 97 

### ISSUE THREAD

**Issue by andrewatduckpin** [CodyHouse/cd-immersive-section-transition-changelog#1]
Nothing happens on the demo with a Windows 11 // Chrome 97 combo. Trying this demo without experiencing the effect:
https://codyhouse.co/ds/components/app/immersive-section-transition

**Comment by claudia-romano** [comment]
Hi there, the effect is disabled if the reduced motion setting is on. Could you double check that? Thanks!

**Comment by andrewatduckpin** [comment]
@claudia-romano Unfortunately I'm testing with browserstack and don't think I can change OS-level settings. Though I don't believe browserstack enables OS-level accessibility settings by default.

Do you have browserstack? If so, I'm using the Windows 11 // Chrome 97 combination for reproducing the issue.

**Comment by claudia-romano** [comment]
Hi there,
I tested it on Window10/Chrome 97 (real machine) and everything is working fine.

There are some cases where the effect does not work. More info here:
https://codyhouse.co/ds/components/info/immersive-section-transition#effect-disabled

If yours is not one of those cases, could you test the demo on Windows10/Chrome97?  Thanks

**Comment by claudia-romano** [comment]
I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
